import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LanguageContext = createContext(null);

const translations = {
  pt: {
    locale: "pt-BR",
    nav: {
      marketplace: "Marketplace",
      collection: "Minha Coleção",
      favorites: "Favoritos",
      listings: "Meus Anúncios",
      trades: "Trocas",
      login: "Entrar",
      signup: "Cadastre-se",
      logout: "Sair da conta",
      openMenu: "Abrir menu",
      closeMenu: "Fechar menu",
      navigation: "Navegação principal",
      themeToggle: "Alternar para modo {mode}",
      light: "claro",
      dark: "escuro",
      language: "Idioma",
      switchToEnglish: "Switch to English",
    },
    common: {
      close: "Fechar",
      cancel: "Cancelar",
      confirm: "Confirmar",
      error: "Erro",
      loading: "Carregando...",
      unknownCard: "Carta desconhecida",
      noImage: "Sem imagem",
      yesCancel: "Sim, cancelar",
      no: "Não",
      ok: "Ok",
      seller: "Vendedor",
      credits: "cr",
      directPurchase: "Compra Direta",
      auction: "Leilão",
      sale: "Venda",
      active: "Ativos",
      ended: "Encerrado",
      cardFallback: "Carta",
    },
    home: {
      badge: "Marketplace Oficial",
      title: "Temos que colecionar!",
      subtitle:
        "Descubra, compre e acompanhe suas cartas favoritas de Pokémon TCG em tempo real.",
      tabs: {
        all: "Todos",
        sale: "À Venda",
        auction: "Leilões",
      },
      tabLabel: "Filtrar anúncios",
      loading: "Carregando marketplace...",
      loadError: "Erro ao carregar o marketplace.",
      empty: "Nenhum anúncio encontrado.",
      loadMore: "Carregar mais",
      buySuccessTitle: "Compra realizada",
      buySuccess: '"{name}" comprada com sucesso!',
      buyError: "Erro ao comprar carta.",
      favoriteError: "Erro ao atualizar favoritos.",
    },
    search: {
      explore: "Explorar Cartas",
      searchLabel: "Buscar carta por nome",
      placeholder: "Buscar por nome...",
      rarity: "Raridade:",
      condition: "Condição:",
      all: "Todas",
      rarities: {
        Common: "Comum",
        Uncommon: "Incomum",
        Rare: "Rara",
        "Rare Holo": "Rara Holo",
        Promo: "Promocional",
        "Rare Holo EX": "Rara Holo EX",
        "Ultra Rare": "Ultra Rara",
        "Secret Rare": "Rara Secreta",
      },
      conditions: {
        NM: "Muito conservada",
        LP: "Pouco usada",
        MP: "Moderadamente usada",
        HP: "Muito usada",
        DMG: "Danificada",
      },
    },
    card: {
      viewDetails: "Ver detalhes de {name}",
      buy: "Comprar",
      buyCard: "Comprar {name}",
      bid: "Dar Lance",
      bidCard: "Dar lance em {name}",
      auctionActive: "Leilão ativo",
      ownListing: "Seu anúncio",
      auctionEnds: "Leilão termina",
      currentBid: "Lance atual",
    },
    detail: {
      close: "Fechar detalhes da carta",
      currentBid: "Lance atual",
      auctionEnds: "Leilão termina",
      placeBid: "Dar lance",
      bidPlaceholder: "Informe o valor do lance",
      bidRequired: "Informe um valor de lance",
      bidTooLow: "O lance deve ser maior que o lance atual",
      bidSuccess: "Lance enviado com sucesso!",
      bidError: "Erro ao dar lance.",
      startingBid: "Lance inicial",
      loginToInteract: "Entre para interagir",
      tradeOffer: "Propor troca",
    },
    collection: {
      title: "Coleção",
      subtitle: "Busque no catálogo e gerencie suas cartas.",
      tabs: {
        collection: "Minha Coleção",
        catalog: "Buscar Catálogo",
        allCards: "Todas as Cartas",
      },
      tabLabel: "Seções da coleção",
      loading: "Carregando coleção...",
      loadError: "Erro ao carregar a coleção.",
      empty: "Sua coleção está vazia.",
      emptyHint: "Busque no catálogo e adicione suas cartas!",
      noCards: "Nenhuma carta encontrada.",
      announce: "Anunciar",
      announceCard: "Anunciar {name}",
      listed: "Já anunciada",
      remove: "Remover",
      removeCard: "Remover {name} da coleção",
      favoriteAdd: "Adicionar {name} aos favoritos",
      favoriteRemove: "Remover {name} dos favoritos",
      favoriteAddTitle: "Adicionar aos favoritos",
      favoriteRemoveTitle: "Remover dos favoritos",
      favoriteError: "Erro ao atualizar favoritos.",
      removeError: "Erro ao remover carta.",
      owner: "Dono",
      allCardsSearchLabel: "Buscar cartas de todos os usuários",
      allCardsPlaceholder: "Buscar cartas de todos os usuários...",
      pageIndicator: "Página {page} de {total}",
      userCardId: "ID",
    },
    catalog: {
      searchLabel: "Buscar carta no catálogo",
      placeholder: "Buscar carta no catálogo...",
      searching: "Buscando...",
      empty: "Nenhuma carta encontrada.",
      add: "Adicionar à Coleção",
      addCard: "Adicionar {name} à coleção",
    },
    addCard: {
      close: "Fechar modal de adicionar carta",
      condition: "Condição",
      proof: "Foto de prova",
      proofPreview: "Prévia da foto de prova selecionada",
      proofRequired: "Anexe uma foto de prova.",
      addError: "Erro ao adicionar carta.",
      uploading: "Enviando imagem...",
      saving: "Salvando...",
      confirm: "Confirmar",
    },
    listing: {
      close: "Fechar modal de anúncio",
      fixedPrice: "Preço Fixo",
      auction: "Leilão",
      price: "Preço (créditos)",
      priceLabel: "Preço em créditos",
      startingBid: "Lance inicial (créditos)",
      startingBidLabel: "Lance inicial em créditos",
      minIncrement: "Incremento mínimo (créditos)",
      minIncrementLabel: "Incremento mínimo em créditos",
      auctionEnds: "Encerramento do leilão",
      auctionEndsLabel: "Data e hora de encerramento do leilão",
      invalidPrice: "Informe um preço válido.",
      auctionRequired: "Preencha todos os campos do leilão.",
      createError: "Erro ao criar anúncio.",
      createdTitle: "Anúncio criado",
      saleCreated: "Seu anúncio de venda foi criado com sucesso.",
      auctionCreated: "Seu leilão foi criado com sucesso.",
      announcing: "Anunciando...",
      confirm: "Confirmar Anúncio",
    },
    favorites: {
      title: "Favoritos",
      subtitle: "Cartas que você está acompanhando.",
      loading: "Carregando favoritos...",
      loadError: "Erro ao carregar favoritos.",
      empty: "Nenhum favorito ainda.",
      emptyHint: "Favorite uma carta no Marketplace para salvá-la aqui!",
      remove: "Remover {name} dos favoritos",
      removeTitle: "Remover dos favoritos",
      removeError: "Erro ao remover favorito.",
    },
    listings: {
      title: "Meus Anúncios",
      subtitle: "Gerencie seus anúncios ativos no marketplace.",
      active: "Ativos",
      tabs: {
        all: "Todos",
        sale: "Anúncios",
        auction: "Leilões",
      },
      tabLabel: "Filtrar meus anúncios",
      loading: "Carregando anúncios...",
      loadError: "Erro ao carregar seus anúncios.",
      empty: "Nenhum anúncio ativo.",
      emptyHint: "Vá para Minha Coleção e anuncie uma carta!",
      currentBid: "Lance atual:",
      cancel: "Cancelar Anúncio",
      cancelTitle: "Cancelar anúncio",
      cancelMessage: "Tem certeza que deseja cancelar este anúncio?",
      canceledTitle: "Anúncio cancelado",
      canceledMessage: "Seu anúncio foi cancelado com sucesso.",
      cancelError: "Erro ao cancelar anúncio.",
    },
    trades: {
      title: "Trocas e Compras",
      subtitle: "Gerencie suas propostas de troca e histórico de compras.",
      tabs: {
        sent: "Trocas Enviadas",
        received: "Trocas Recebidas",
        purchases: "Minhas Compras",
      },
      tabLabel: "Seções de trocas e compras",
      loading: "Carregando...",
      loadError: "Erro ao carregar os dados.",
      empty: "Nada por aqui ainda.",
      emptyPurchases: "Seu histórico de compras aparecerá aqui.",
      emptyTrades: "Propostas de troca aparecerão aqui.",
      proposal: "Proposta de troca de cartas Pokémon",
      accept: "Aceitar",
      accepting: "Aceitando...",
      acceptedTitle: "Troca aceita",
      acceptedMessage:
        "A proposta foi aceita. Se alguma carta estava anunciada, o anúncio foi cancelado automaticamente.",
      acceptError: "Erro ao aceitar a troca.",
      acceptTitle: "Aceitar troca?",
      acceptMessage:
        "Ao aceitar, as cartas serão transferidas entre os usuários. Se alguma carta envolvida estiver anunciada, o anúncio será cancelado automaticamente.",
      seller: "Vendedor:",
    },
    tradeModal: {
      title: "Propor troca por {name}",
      choose: "Escolha uma carta da sua coleção:",
      loading: "Carregando sua coleção...",
      empty: "Você não tem cartas disponíveis para troca.",
      submitting: "Enviando...",
      offer: "Oferecer",
      sentTitle: "Proposta enviada",
      sentMessage:
        "Proposta enviada (id: {id}): {offered} → {requested}. A troca só será concluída quando o dono da carta aceitar a proposta.",
      loadError: "Erro ao carregar sua coleção.",
      sendError: "Erro ao enviar proposta.",
    },
    auth: {
      loginTitle: "Bem-vindo de volta",
      loginSubtitle: "Entre para acessar sua coleção.",
      registerTitle: "Criar conta",
      registerSubtitle: "Entre no PocketMarket e comece sua coleção.",
      email: "Email",
      password: "Senha",
      name: "Nome",
      forgotPassword: "Esqueceu a senha?",
      loginButton: "Entrar",
      loginLoading: "Entrando...",
      registerButton: "Cadastrar",
      registerLoading: "Criando conta...",
      loginMissing: "Preencha email e senha.",
      registerMissing: "Preencha todos os campos.",
      loginError: "Email ou senha inválidos.",
      registerError: "Erro ao criar conta. Tente novamente.",
      noAccount: "Não tem conta?",
      hasAccount: "Já tem conta?",
      signUp: "Cadastre-se",
      logIn: "Entrar",
      namePlaceholder: "Ash Ketchum",
    },
    accessibility: {
      skipMain: "Pular para o conteúdo principal",
      closeDialog: "Fechar diálogo",
      timer: "Tempo restante: {time}",
    },
  },
  en: {
    locale: "en-US",
    nav: {
      marketplace: "Marketplace",
      collection: "My Collection",
      favorites: "Favorites",
      listings: "My Listings",
      trades: "Trades",
      login: "Login",
      signup: "Sign Up",
      logout: "Log out",
      openMenu: "Open menu",
      closeMenu: "Close menu",
      navigation: "Main navigation",
      themeToggle: "Switch to {mode} mode",
      light: "light",
      dark: "dark",
      language: "Language",
      switchToEnglish: "Mudar para Português",
    },
    common: {
      close: "Close",
      cancel: "Cancel",
      confirm: "Confirm",
      error: "Error",
      loading: "Loading...",
      unknownCard: "Unknown Card",
      noImage: "No image",
      yesCancel: "Yes, cancel",
      no: "No",
      ok: "OK",
      seller: "Seller",
      credits: "cr",
      directPurchase: "Direct Purchase",
      auction: "Auction",
      sale: "Sale",
      active: "Active",
      ended: "Ended",
      cardFallback: "Card",
    },
    home: {
      badge: "Official Marketplace",
      title: "Gotta collect 'em all",
      subtitle:
        "Discover, buy, and track the value of your favorite Pokémon TCG cards in real time.",
      tabs: {
        all: "All",
        sale: "For Sale",
        auction: "Auctions",
      },
      tabLabel: "Filter listings",
      loading: "Loading marketplace...",
      loadError: "Error loading marketplace.",
      empty: "No listings found.",
      loadMore: "Load More",
      buySuccessTitle: "Purchase completed",
      buySuccess: '"{name}" purchased successfully!',
      buyError: "Error buying card.",
      favoriteError: "Error updating favorites.",
    },
    search: {
      explore: "Explore Cards",
      searchLabel: "Search card by name",
      placeholder: "Search by name...",
      rarity: "Rarity:",
      condition: "Condition:",
      all: "All",
      rarities: {
        Common: "Common",
        Uncommon: "Uncommon",
        Rare: "Rare",
        "Rare Holo": "Rare Holo",
        Promo: "Promo",
        "Rare Holo EX": "Rare Holo EX",
        "Ultra Rare": "Ultra Rare",
        "Secret Rare": "Secret Rare",
      },
      conditions: {
        NM: "Near Mint",
        LP: "Lightly Played",
        MP: "Moderately Played",
        HP: "Heavily Played",
        DMG: "Damaged",
      },
    },
    card: {
      viewDetails: "View details for {name}",
      buy: "Buy",
      buyCard: "Buy {name}",
      bid: "Place Bid",
      bidCard: "Place bid on {name}",
      auctionActive: "Auction Active",
      ownListing: "Your listing",
      auctionEnds: "Auction Ends",
      currentBid: "Current Bid",
    },
    detail: {
      close: "Close card details",
      currentBid: "Current Bid",
      auctionEnds: "Auction Ends",
      placeBid: "Place Bid",
      bidPlaceholder: "Enter bid amount",
      bidRequired: "Enter a bid amount",
      bidTooLow: "Bid must be higher than current bid",
      bidSuccess: "Bid submitted successfully!",
      bidError: "Error placing bid.",
      startingBid: "Starting bid",
      loginToInteract: "Login to interact",
      tradeOffer: "Trade Offer",
    },
    collection: {
      title: "Collection",
      subtitle: "Search the catalog and manage your cards.",
      tabs: {
        collection: "My Collection",
        catalog: "Search Catalog",
      },
      tabLabel: "Collection sections",
      loading: "Loading collection...",
      loadError: "Error loading collection.",
      empty: "Your collection is empty.",
      emptyHint: "Search the catalog and add your cards!",
      announce: "List",
      announceCard: "List {name}",
      listed: "Already listed",
      remove: "Remove",
      removeCard: "Remove {name} from collection",
      favoriteAdd: "Add {name} to favorites",
      favoriteRemove: "Remove {name} from favorites",
      favoriteAddTitle: "Add to favorites",
      favoriteRemoveTitle: "Remove from favorites",
      favoriteError: "Error updating favorites.",
      removeError: "Error removing card.",
    },
    catalog: {
      searchLabel: "Search card in catalog",
      placeholder: "Search card in catalog...",
      searching: "Searching...",
      empty: "No card found.",
      add: "Add to Collection",
      addCard: "Add {name} to collection",
    },
    addCard: {
      close: "Close add card modal",
      condition: "Condition",
      proof: "Proof photo",
      proofPreview: "Preview of selected proof photo",
      proofRequired: "Attach a proof photo.",
      addError: "Error adding card.",
      uploading: "Uploading image...",
      saving: "Saving...",
      confirm: "Confirm",
    },
    listing: {
      close: "Close listing modal",
      fixedPrice: "Fixed Price",
      auction: "Auction",
      price: "Price (credits)",
      priceLabel: "Price in credits",
      startingBid: "Starting bid (credits)",
      startingBidLabel: "Starting bid in credits",
      minIncrement: "Minimum increment (credits)",
      minIncrementLabel: "Minimum increment in credits",
      auctionEnds: "Auction ends",
      auctionEndsLabel: "Auction end date and time",
      invalidPrice: "Enter a valid price.",
      auctionRequired: "Fill in every auction field.",
      createError: "Error creating listing.",
      createdTitle: "Listing created",
      saleCreated: "Your sale listing was created successfully.",
      auctionCreated: "Your auction was created successfully.",
      announcing: "Listing...",
      confirm: "Confirm Listing",
    },
    favorites: {
      title: "Favorites",
      subtitle: "Cards you are keeping an eye on.",
      loading: "Loading favorites...",
      loadError: "Error loading favorites.",
      empty: "No favorites yet.",
      emptyHint: "Heart a card in the Marketplace to save it here!",
      remove: "Remove {name} from favorites",
      removeTitle: "Remove from favorites",
      removeError: "Error removing favorite.",
    },
    listings: {
      title: "My Listings",
      subtitle: "Manage your active listings on the marketplace.",
      active: "Active",
      tabs: {
        all: "All",
        sale: "Listings",
        auction: "Auctions",
      },
      tabLabel: "Filter my listings",
      loading: "Loading listings...",
      loadError: "Error loading your listings.",
      empty: "No active listings.",
      emptyHint: "Go to My Collection and list a card!",
      currentBid: "Current bid:",
      cancel: "Cancel Listing",
      cancelTitle: "Cancel listing",
      cancelMessage: "Are you sure you want to cancel this listing?",
      canceledTitle: "Listing canceled",
      canceledMessage: "Your listing was canceled successfully.",
      cancelError: "Error canceling listing.",
    },
    trades: {
      title: "Trades & Purchases",
      subtitle: "Manage your trade offers and purchase history.",
      tabs: {
        sent: "Sent Trades",
        received: "Received Trades",
        purchases: "My Purchases",
      },
      tabLabel: "Trades and purchases sections",
      loading: "Loading...",
      loadError: "Error loading data.",
      empty: "Nothing here yet.",
      emptyPurchases: "Your purchase history will appear here.",
      emptyTrades: "Trade offers will appear here.",
      proposal: "Pokémon card trade proposal",
      accept: "Accept",
      accepting: "Accepting...",
      acceptedTitle: "Trade accepted",
      acceptedMessage:
        "The offer was accepted. If any card was listed, the listing was automatically canceled.",
      acceptError: "Error accepting trade.",
      acceptTitle: "Accept trade?",
      acceptMessage:
        "When accepted, the cards will be transferred between users. If any involved card is listed, the listing will be canceled automatically.",
      seller: "Seller:",
    },
    tradeModal: {
      title: "Trade offer for {name}",
      choose: "Choose a card from your collection:",
      loading: "Loading your collection...",
      empty: "You do not have available cards for trade.",
      submitting: "Sending...",
      offer: "Offer",
      sentTitle: "Offer sent",
      sentMessage:
        "Offer sent (id: {id}): {offered} → {requested}. The trade will only be completed when the card owner accepts the offer.",
      loadError: "Error loading your collection.",
      sendError: "Error sending offer.",
      invalidCard: "The selected card is missing required trade data.",
    },
    auth: {
      loginTitle: "Welcome back",
      loginSubtitle: "Enter your credentials to access your collection.",
      registerTitle: "Create account",
      registerSubtitle: "Join PocketMarket and start your collection.",
      email: "Email Address",
      password: "Password",
      name: "Name",
      forgotPassword: "Forgot password?",
      loginButton: "Log In",
      loginLoading: "Signing in...",
      registerButton: "Sign Up",
      registerLoading: "Creating account...",
      loginMissing: "Fill in email and password.",
      registerMissing: "Fill in every field.",
      loginError: "Invalid email or password.",
      registerError: "Error creating account. Try again.",
      noAccount: "Don't have an account?",
      hasAccount: "Already have an account?",
      signUp: "Sign Up",
      logIn: "Log In",
      namePlaceholder: "Ash Ketchum",
    },
    accessibility: {
      skipMain: "Skip to main content",
      closeDialog: "Close dialog",
      timer: "Time left: {time}",
    },
  },
};

function getNestedValue(object, path) {
  return path.split(".").reduce((acc, key) => acc?.[key], object);
}

function interpolate(text, params) {
  if (!params) return text;
  return Object.entries(params).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, value ?? ""),
    text,
  );
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem("language") || "pt",
  );

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language === "pt" ? "pt-BR" : "en";
  }, [language]);

  const value = useMemo(() => {
    function t(path, params) {
      const text =
        getNestedValue(translations[language], path) ??
        getNestedValue(translations.pt, path) ??
        path;

      return typeof text === "string" ? interpolate(text, params) : text;
    }

    function toggleLanguage() {
      setLanguage((current) => {
        const next = current === "pt" ? "en" : "pt";
        return next;
      });
    }

    return {
      language,
      locale: translations[language].locale,
      setLanguage,
      t,
      toggleLanguage,
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  return useContext(LanguageContext);
}
